# Generated by Django 5.2.14 on 2026-05-31 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.IntegerField(verbose_name='Номер свердловини')),
                ('area', models.CharField(max_length=100, verbose_name='Площа')),
            ],
            options={
                'verbose_name': 'Свердловина',
                'verbose_name_plural': 'Свердловини',
                'ordering': ['well_number'],
            },
        ),
        migrations.CreateModel(
            name='RockSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50, verbose_name='Зразок №')),
                ('rock_type', models.CharField(max_length=50, verbose_name='Порода')),
                ('mag_susceptibility', models.FloatField(verbose_name='Магнітна сприйнятливість')),
                ('depth', models.FloatField(blank=True, null=True, verbose_name='Інтервал (глибина)')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.well', verbose_name='Свердловина')),
            ],
            options={
                'verbose_name': 'Зразок породи',
                'verbose_name_plural': 'Зразки порід',
            },
        ),
    ]
